[project]
id = "wisebook"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:5178"
additional_redirect_urls = ["http://localhost:5178"]
jwt_expiry = 3600
enable_signup = true
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.mfa]
enabled = true
max_enrolled_factors = 10

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[analytics]
enabled = false
